---
version: "2"
exclude_patterns:
  # Bundled thirdparty asset files
  - "app/assets/javascripts/app/lib/**/*.js"
  - "config/"
  - "db/"
  - "**/node_modules/"
  - "script/"
  - "public/assets/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "**/vendor/"
  - "**/*.d.ts"
